import type { Metadata } from "next";
import { Clock, Instagram, Mail, MapPin, Phone } from "lucide-react";
import { business } from "@/lib/business";
import PageHero from "@/components/PageHero";
import QuoteForm from "@/components/QuoteForm";

export const metadata: Metadata = { title: `Contact | ${business.businessName}`, description: `Send a cleaning enquiry in ${business.city}.` };
export default async function ContactPage({ searchParams }: { searchParams: Promise<{ service?: string }> }) {
  const { service = "" } = await searchParams;
  return <><PageHero eyebrow={`Contact ${business.logoText}`} title="Ready for Your Home to Glow?" description="Send what you need cleaned, your suburb, and your preferred day. Celestial Glow will get back to you with availability." showCta={false} />
    <section className="section pt-8"><div className="shell grid items-start gap-10 lg:grid-cols-[.65fr_1fr]"><aside className="space-y-5 lg:sticky lg:top-24">
      <div className="card p-7"><h2 className="font-[var(--font-display)] text-2xl font-extrabold">Message to book</h2><div className="mt-6 space-y-5">{business.socialLinks[0] && <a href={business.socialLinks[0].href} target="_blank" rel="noreferrer" className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-amber-50 text-[var(--primary)]"><Instagram size={19} /></span><span><small className="block text-slate-500">Instagram</small><strong>{business.instagram}</strong></span></a>}{business.phoneHref && <a href={`tel:${business.phoneHref}`} className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-amber-50 text-[var(--primary)]"><Phone size={19} /></span><span><small className="block text-slate-500">Call</small><strong>{business.phone}</strong></span></a>}{business.email && <a href={`mailto:${business.email}`} className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-amber-50 text-[var(--primary)]"><Mail size={19} /></span><span className="min-w-0"><small className="block text-slate-500">Email</small><strong className="break-all text-sm">{business.email}</strong></span></a>}<div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-amber-50 text-[var(--primary)]"><Clock size={19} /></span><span><small className="block text-slate-500">Availability</small>{business.businessHours.map(h => <strong key={h} className="block text-sm">{h}</strong>)}</span></div></div></div>
      <div className="rounded-[1.75rem] border border-pink-100 bg-[#fff3f7] p-7"><MapPin className="text-[var(--secondary)]" /><h2 className="mt-4 text-xl font-extrabold">Serving {business.city}, WA</h2><p className="mt-3 leading-7 text-slate-600">Send your suburb with your message and Celestial Glow will confirm whether your area is covered.</p></div>
    </aside><div><h2 className="mb-6 font-[var(--font-display)] text-3xl font-extrabold">Send Enquiry</h2><QuoteForm initialService={service} /></div></div></section></>;
}
